# SITE CONFIGURATION
title: Leticia Portella # your site title
author: leportella # You :P
description: > # Meta description of Homepage
    This a blog from an oceanographer who became passionare about programming.
    I'm a dev, in love with data science that loves to write technical posts
    about what I'm learning, specially Python, Django and Data Science stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leportella.com"

# SEO PLUGIN
social:
  name: leportella
  links:
    - https://twitter.com/leleportella
    - https://www.linkedin.com/in/leportella
    - https://github.com/leportella

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about.html'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Talks', link: '/talks'}
  - {name: 'ðŸ‡§ðŸ‡· Posts', link: '/pt-br'}
  - {name: 'ðŸ‡¬ðŸ‡§ Posts', link: '/en'}


tagline: >
    random thoughts about life, tech and career

hero_img: posts/ocean.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: leportella@protonmail.com

twitter_username: leleportella
github_username: leportella

disqus:
  shortname: leportella-com

google_analytics: UA-106178084-1
google_tag_manager: UA-106178084-1 

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
#permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
