# SITE CONFIGURATION
title: leportella # your site title
author: leportella # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leportella.com"

# SEO PLUGIN
social:
  name: leportella
  links:
    - https://twitter.com/leleportella
    - https://www.linkedin.com/in/leportella
    - https://github.com/leportella

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about.html'}
  - {name: 'Community Work', link: '/community.html'}
  - {name: 'Curriculum', link: '/curriculum.html'}

tagline: >
    a little bit about me

hero_img: posts/ocean.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

twitter_username: leleportella
github_username: leportella

disqus:
  shortname: leportella-com

google_analytics: UA-106178084-1
# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
#permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
